name: Main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn
      - name: Run unit-tests
        run: yarn test

  build-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Configure Git
        run: |
          git config --local user.email "ci@github-actions.com"
          git config --local user.name "github bot"
          git remote -v
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: lerna publish prerelease --no-commit-hooks --yes --contents dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
