name: Main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn
      - name: Run unit-tests
        run: yarn test

  build-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm whoami
      - run: lerna publish --yes --contents dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


